# Generated by Django 3.2.17 on 2023-12-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('features', models.ManyToManyField(blank=True, to='property.Features')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=10)),
                ('rental_cost', models.FloatField(max_length=30)),
                ('interior', models.CharField(choices=[('N', '1 BHK'), ('S', '2 BHK'), ('F', '4 BHK')], max_length=1)),
                ('type', models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK')], max_length=5)),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='property.propertyprofile')),
            ],
        ),
    ]
