# Generated by Django 3.2.17 on 2023-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertyprofile_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='interior',
            field=models.CharField(choices=[('Not Furnished', 'Not Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Fully Furnished', 'Fully Furnished')], max_length=20),
        ),
    ]
