# Generated by Django 3.2.17 on 2023-12-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(default='Nil', max_length=30)),
                ('tenant_address', models.TextField(default='Nil', max_length=100)),
                ('agreement_end_date', models.DateField(default='1960-01-01')),
                ('monthly_rent_date', models.TextField(default='1960-01-01')),
                ('document_proofs', models.TextField(default='Nil', max_length=100)),
                ('property_unit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='property.propertyunit')),
            ],
        ),
    ]
