# Generated by Django 3.2.17 on 2023-12-02 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertyunit_interior'),
        ('tenantprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='property_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertyunit'),
        ),
    ]
