# Generated by Django 3.2.17 on 2023-12-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertyunit_interior'),
        ('tenantprofile', '0003_auto_20231202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='property_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertyunit'),
        ),
    ]
